# Generated by Django 4.1.7 on 2023-10-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_email',
            field=models.EmailField(default=None, max_length=254, null=True, unique=True),
        ),
    ]
