# Generated by Django 4.1.7 on 2023-09-07 04:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ram', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=100)),
                ('front_camera', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('image', models.FileField(upload_to='mobiles/')),
                ('price', models.FloatField(default=0)),
                ('price_off', models.FloatField(blank=True, default=0, null=True)),
                ('storage', models.CharField(max_length=100)),
                ('popularity', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brand')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.catagory')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.colour')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Others_Details',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.CharField(max_length=100)),
                ('sim_type', models.CharField(max_length=100)),
                ('expandible_storage', models.CharField(max_length=100)),
                ('audio_jack', models.CharField(max_length=100)),
                ('quick_charge', models.CharField(max_length=100)),
                ('in_the_box', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('highlights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_details', related_query_name='other_details', to='home.highlights')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_details', related_query_name='other_details', to='home.mobile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='highlights',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', related_query_name='highlights', to='home.mobile'),
        ),
    ]
