# Generated by Django 4.1.7 on 2023-10-18 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_others_details_highlights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=3000)),
                ('price', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('reviews', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
