# Generated by Django 4.1.7 on 2023-10-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_mobiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobiles',
        ),
    ]
