# Generated by Django 4.1.7 on 2023-10-19 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_mobiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Product_Name', models.CharField(max_length=100000)),
                ('Product_Price', models.CharField(max_length=100)),
                ('Product_Reviews', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
